=== roman1306/xml-practice/src/main/resources/goods.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="storage">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="category" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="subcategory" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="product" type="characteristic" maxOccurs="unbounded"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="name" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="name" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="characteristic">
        <xsd:sequence>
            <xsd:element name="maker" type="xsd:string"/>
            <xsd:element name="model">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-zA-Z]{2}[0-9]{3}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="productionDate" type="xsd:date"/>
            <xsd:element name="color" type="xsd:string"/>
            <xsd:element name="price">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:double">
                            <xsd:attribute name="available" type="xsd:boolean" use="required"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== roman1306/xml-practice/Implementation/src/main/resources/qa/goods.xml
<?xml version="1.0" encoding="UTF-8"?>

<storage xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
        xsd:noNamespaceSchemaLocation="goods.xsd">


    <category name="telephones and gadgets for qa">
        <subcategory name="telephones">
            <product>
                <maker>limbo</maker>
                <model>ab163</model>
                <productionDate>2019-09-24</productionDate>
                <color>red</color>
                <price available="false">35.8</price>
            </product>
        </subcategory>
        <subcategory name="plane table">
            <product>
                <maker>gray</maker>
                <model>df165</model>
                <productionDate>2019-09-24</productionDate>
                <color>white</color>
                <price available="true">10</price>
            </product>
        </subcategory>
    </category>

    <category name="domestic appliances">
        <subcategory name="vacuum cleaners">
            <product>
                <maker>limbo</maker>
                <model>fr471</model>
                <productionDate>2019-09-24</productionDate>
                <color>yellow</color>
                <price available="false">85</price>
            </product>
        </subcategory>
        <subcategory name="fridges">
            <product>
                <maker>frank</maker>
                <model>bg646</model>
                <productionDate>2019-09-24</productionDate>
                <color>green</color>
                <price available="false">25.9</price>
            </product>
        </subcategory>
    </category>

    <category name="computers">
        <subcategory name="PC">
            <product>
                <maker>stark</maker>
                <model>gf888</model>
                <productionDate>2019-09-24</productionDate>
                <color>red</color>
                <price available="true">75</price>
            </product>
        </subcategory>
        <subcategory name="laptop">
            <product>
                <maker>stark</maker>
                <model>xs789</model>
                <productionDate>2019-09-24</productionDate>
                <color>blue</color>
                <price available="true">25.5</price>
            </product>
        </subcategory>
    </category>

</storage>
